version: '3'
services:
  database:
    image: mongo:latest
    container_name: open-jira-db
    ports:
      - "27017:27017"
    volumes:
      - "./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"